export const postInfo = [
    {
        id:'1',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'published',
        stats:'120',
    },
    {
        id:'2',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'draft',
        stats:'00',
    },
    {
        id:'3',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'scheduled',
        stats:'00',
    },
    {
        id:'4',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'published',
        stats:'120',
    },
    {
        id:'5',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'published',
        stats:'120',
    },
    {
        id:'6',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'scheduled',
        stats:'00',
    },
    {
        id:'7',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'published',
        stats:'120',
    },
    {
        id:'8',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'draft',
        stats:'00',
    },
    {
        id:'9',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'scheduled',
        stats:'00',
    },
    {
        id:'10',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'draft',
        stats:'00',
    },
    {
        id:'11',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'published',
        stats:'120',
    },
    {
        id:'12',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'scheduled',
        stats:'00',
    },
    {
        id:'13',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'published',
        stats:'120',
    },
    {
        id:'14',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'published',
        stats:'120',
    },
    {
        id:'15',
        title:'Design: A Survival Guide for Beginners',
        subtitle:'Posted 3 days ago',
        status:'scheduled',
        stats:'00',
    },
]
